version: '3'

services:

  postgis:
    container_name: postgis
    image: "mdillon/postgis"
    restart: always
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pw
      - POSTGRES_DB=postgres_db
    ports:
      - 54320:5432
    volumes:
      # File container for the DB
      - ./postgres-data:/var/lib/postgresql/data
      # GTFS DB schema initialization files. Postgis image has to execute 'postgis.sh'
      # first so we have to name our scripts 'q*'. This is because scripts are executed
      # in alphabetic order in the docker-entrypoint-initdb.d/ folder
      - ./db-specification/gtfs_table_creation.sql:/docker-entrypoint-initdb.d/q-init-1.sql
      - ./db-specification/gtfs_table_add_constraints.sql:/docker-entrypoint-initdb.d/q-init-2.sql